#!/usr/bin/env bash
#
# Copyright (c) 2014 blackchip.org
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

set -x

apt-get update
apt-get install -y \
    alsa-utils \
    curl \
    libboost-dev \
    python-imaging \
    python-pyglet \
    python-pygame \
    python-setuptools \
    python-tk \
    swig

curl -O http://www.blackchip.org/precise64/local-libftdi-0.16_amd64.deb
curl -O http://www.blackchip.org/precise64/local-libpinproc-0.0.0_amd64.deb
curl -O http://www.blackchip.org/precise64/local-libusb-0.1.12_amd64.deb
curl -O http://www.blackchip.org/precise64/local-pypinproc-0.0.0_amd64.deb
dpkg --install *.deb

ldconfig

amixer -c 0 -- sset Master 100% unmute
amixer -c 0 -- sset PCM 100% unmute
aplay /usr/share/sounds/alsa/Front_Center.wav
aplay /usr/share/sounds/alsa/Noise.wav
usermod -a -G audio vagrant

mkdir /home/vagrant/.pyprocgame
ln -s /vagrant/config/system.json /home/vagrant/.pyprocgame/config.json

cat > /usr/local/bin/pingame <<EOF
#/bin/bash

export DISPLAY=$(ip route show default | head -1 | awk '{print $3}'):0
( cd /vagrant ; python -m pingame )
EOF
chmod 755 /usr/local/bin/pingame
