#!/usr/bin/env bash
#
# Copyright (c) 2014 blackchip.org
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

set -x

apt-get update
apt-get install -y \
    alsa-utils \
    cmake \
    curl \
    git \
    g++ \
    libboost-dev \
    libyaml-dev \
    make \
    python-dev \
    python-imaging \
    python-pyglet \
    python-pygame \
    python-yaml \
    python-setuptools \
    swig

curl -L -O 'http://softlayer-dal.dl.sourceforge.net/project/libusb/libusb-0.1%20%28LEGACY%29/0.1.12/libusb-0.1.12.tar.gz'
tar xf libusb-0.1.12.tar.gz
( cd libusb-0.1.12 ;
    ./configure ;
    make ;
    make install)

curl -O http://yaml-cpp.googlecode.com/files/yaml-cpp-0.3.0.tar.gz
tar xf yaml-cpp-0.3.0.tar.gz
mkdir -p yaml-cpp/build
( cd yaml-cpp/build ; \
    cmake .. ; \
    make ; \
    make install )

curl -O http://www.intra2net.com/en/developer/libftdi/download/libftdi-0.16.tar.gz
tar xf libftdi-0.16.tar.gz
mkdir -p libftdi-0.16/build
( cd libftdi-0.16/build ; \
    cmake .. ; \
    make ; \
    make install )
ln -s /usr/local/include/libftdi/ftdi.h /usr/local/include/ftdi.h
ln -s /usr/local/lib/libftdi.so.1 /usr/local/lib/libftdi1.so

git clone https://github.com/preble/libpinproc.git
mkdir -p libpinproc/bin
( cd libpinproc/bin; \
    cmake -DCMAKE_CXX_FLAGS="-fPIC" -DBUILD_SHARED_LIBS="ON" .. ; \
    make ; \
    make install )

git clone https://github.com/preble/pypinproc.git
( cd pypinproc ; \
    python setup.py build ; \
    python setup.py install )

git clone https://github.com/preble/pyprocgame.git
( cd pyprocgame ; \
    python setup.py build ; \
    python setup.py install )

ldconfig

amixer -c 0 -- sset Master 100% unmute
amixer -c 0 -- sset PCM 100% unmute
aplay /usr/share/sounds/alsa/Front_Center.wav
aplay /usr/share/sounds/alsa/Noise.wav
usermod -G audio vagrant
